# Generated by Django 4.2.6 on 2023-10-07 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0003_task_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='img',
            new_name='image',
        ),
    ]
